### ISSUE TITLE
sbl connectivity section fails in some environments

### ISSUE THREAD

**Issue by dl2n** [PowerShell/PrivateCloud.DiagnosticInfo#100]
The SBL connectivity section fails in some environments. Root cause why this is happening and address, either by working around the issue/a new gather pattern or squelching the error so that it is not fatal.

            try {
                $JobStatic += $ClusterNodes |% {
                    $node = $_.Name
                    Start-Job -Name "S2D Connectivity: $node" -InitializationScript $CommonFunc {
                        Get-CimInstance -Namespace root\wmi -ClassName ClusPortDeviceInformation -ComputerName $using:node |
                            Export-Clixml (Join-Path (Get-NodePath $using:Path $using:node) "ClusPort.xml")
                        Get-CimInstance -Namespace root\wmi -ClassName ClusBfltDeviceInformation -ComputerName $using:node |
                            Export-Clixml (Join-Path (Get-NodePath $using:Path $using:node) "ClusBflt.xml")
                    }
                }
            } catch {
                Show-Warning "Gathering SBL connectivity failed"
            }

**Comment by visvel** [comment]
SBL connectivity issue based on the investigation so far I feel its related to constrained language issue so I am tackling constrained language issue first to see if its fixing both.

**Comment by visvel** [comment]
Fixed.
