### ISSUE TITLE
Add Get-ComputerInfo

### ISSUE THREAD

**Issue by jlgandy2** [PowerShell/PrivateCloud.DiagnosticInfo#123]
This would allow us to see things missing from the systeminfo.txt like WindowsBuildLabEx, BiosSeralNumber and others.

**Comment by visvel** [comment]
Is just "Add-ComputerInfo" command fine? Also is this command inclusion going to add real value?

**Comment by jlgandy2** [comment]
Did you add Get-ComputerInfo or Add-ComputerInfo because I am asking for Get-ComputerInfo. This command will give us the missing information from the systeminfo.txt. Ex. BIOS settings including the Serial Number of the server, Windows Build Number per node which is not in the current version, and DeviceGuard policies. Let me know if you need more info.

**Comment by jlgandy2** [comment]
Any update on this?

**Comment by visvel** [comment]
Sorry. Missed this. Will look into it and address this soon.

**Comment by visvel** [comment]
fyi in code review @ https://github.com/PowerShell/PrivateCloud.DiagnosticInfo/pull/126/files

**Comment by visvel** [comment]
Fixed.
