### ISSUE TITLE
Add Get-VmSwitch and Get-VMNetworkAdapter

### ISSUE THREAD

**Issue by jlgandy2** [PowerShell/PrivateCloud.DiagnosticInfo#124]
I see in Issue #93 this was requested and some of it was added to 1.1.1. Can we add these as well? They will help us get the SET switch configuration and the vNIC configuration information.

Get-VMSwitch | FL *
Get-VMNetworkAdapter -ManagementOS | FL *

**Comment by visvel** [comment]
I already see Get-VMSwitch & Get-VMNetworkAdapter captured part of our collection. Are you suggesting to add " | fl *" & " -ManagementOS | FL *" to these commands?

**Comment by jlgandy2** [comment]
Hmm I am not seeing GetVmSwitch.xml or GetVMNetworkAdapter in the output. I am running version  (2019-03-01T16:06:25 : Gathered with       : PrivateCloud.DiagnosticInfo v 1.1.9). Is this the version that has these collected?

**Comment by jlgandy2** [comment]
Any update on why we do not seeing GetVmSwitch.xml or GetVMNetworkAdapter.xml in v1.1.9?  
I do agree with you to add " | fl *" & " -ManagementOS | FL *".

**Comment by visvel** [comment]
I'll look into it and keep this thread updated soon.

**Comment by jlgandy2** [comment]
Any update on this?

**Comment by visvel** [comment]
Sorry. Missed this. Will look into it and address this soon.

**Comment by jlgandy2** [comment]
Thank you. This information will be very useful once its showing up in the output.

**Comment by visvel** [comment]
fyi in code review @ https://github.com/PowerShell/PrivateCloud.DiagnosticInfo/pull/126/files

**Comment by jlgandy2** [comment]
I looked at the code and I see the section with the commands is commented out. Here is a paste from the link above.
        # Re-enable these after root causing cmdlet issues in VM guest clusters (hsun issue)
                <#
                if (Get-Module Hyper-V -ErrorAction SilentlyContinue) {
                    $CmdsToLog += 'Get-VM -CimSession _C_',
                                    'Get-VMNetworkAdapter -All -CimSession _C_',
                                    'Get-VMSwitch -CimSession _C_'
                    $CmdsToLog += 'Get-VM -CimSession _C_ -ErrorAction SilentlyContinue',
                                    'Get-VMNetworkAdapter -All -CimSession _C_ -ErrorAction SilentlyContinue',
                                    'Get-VMSwitch -CimSession _C_ -ErrorAction SilentlyContinue'
                }
                #>

**Comment by jlgandy2** [comment]
Please added |FL * to include everything  as we need to be able to see all the attributes
$CmdsToLog += 'Get-VM -CimSession _C_ | FL *',
                                    'Get-VMNetworkAdapter -All -CimSession _C_ | FL *',
                                    'Get-VMSwitch -CimSession _C_ | FL *'

**Comment by dl2n** [comment]
Please look closer, that’s not how it works.

We specify cmdlets, and capture their output to render in both text and xml forms (import-clixml abc.xml) in the loop just down from where you see the cmd specs. We prefer the default text rendering applied by the cmdlet author to fl * since that may capture some custom post-processing that’s lost in fl; if the full fidelity object is preferred (for that, or other purposes like further programmatic work), that’s why the XML is captured. E.g.:

import-clixml abc.xml | fl *

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jlgandy2** [comment]
AH! Yes I see. Very nice work. When will these be uncommitted so we get the outputs?

**Comment by visvel** [comment]
Fixed.
