### ISSUE TITLE
Register-SddcDiagnosticArchiveJob does not work on Azure Stack

### ISSUE THREAD

**Issue by zyxyoshine** [PowerShell/PrivateCloud.DiagnosticInfo#128]
Azure Stack team want to proactively collect SDDC logs.
I tried Register-SddcDiagnosticArchiveJob to setup the job on a Azure Stack environment (CONSTRAINED LANGUAGE MODE)
But the scheduled job dose not work, because at https://github.com/PowerShell/PrivateCloud.DiagnosticInfo/blob/3b96557c5a15e2a809a79cbb785faa0bed431452/PrivateCloud.DiagnosticInfo/PrivateCloud.DiagnosticInfo.psm1#L3527
the script use `[ref]` which is not supported in the constrained language mode, and will throw:
Cannot create type. Only core types are supported in this language mode.
...
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : CannotCreateTypeConstrainedLanguage
I have tried directly get parameter (replace above line 3527 by the following code):
``` powershell
$c = Get-Cluster -Name . -ErrorAction Stop
$Path = ($c | Get-ClusterParameter -Name SddcDiagnosticArchivePath -ErrorAction Stop).Value
```
And it works as expected.

In addition, we want more parameters to allow us specify the frequency, for example, 4 times / day and including 7 hours of data each time.

**Comment by zyxyoshine** [comment]
@visvel ping, do you have a plan to fix this issue?

**Comment by visvel** [comment]
I'll look into it. Will update you by end of this week.

**Comment by dl2n** [comment]
It would be more appropriate to bring this to an internal thread.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by visvel** [comment]
@zyxyoshine I would want to track this new ask as part of a email thread and later address via a deliverable. So please do the same. So I will close this thread here.
