### ISSUE TITLE
Debug-StorageSubsystem is deprecated in Windows Server 2019, should be use Get-HealthFault instead of export storage faults?

### ISSUE THREAD

**Issue by weiran-ms** [PowerShell/PrivateCloud.DiagnosticInfo#138]
Debug-StorageSubsystem is deprecated in Windows Server 2019, should be use Get-HealthFault instead of export storage faults?

**Comment by visvel** [comment]
I am unaware of this deprecated story. Is there any article which suggests the substitute for Debug-StorageSubsystem?

**Comment by visvel** [comment]
fixed
