### ISSUE TITLE
Provide option for exporting event logs as CSV not EVTX

### ISSUE THREAD

**Issue by wilicon** [PowerShell/PrivateCloud.DiagnosticInfo#146]
Data coming from machines in secure environments will need to be manually scrubbed for confidential information, which most likely means it needs to be plain text.

While this could be done on another machine by a different Powershell script, I've received multiple requests asking for such a feature in get-sddcdiagnosticinfo itself:  engineers have pointed out their dev machines often don’t have many of the modules of the customer machines, so they can’t convert event data to text locally.  Also, they’re having trouble opening multiple large event logs at the same time in .evtx format.

**Comment by dl2n** [comment]
SDDC has been exporting the event conversion metadata since v1.1.1 circa October 2018, which allows full rendering inside anything using the standard event toolchain (Message Analyzer, Event Viewer, Get-Event, et.al.).
