### ISSUE TITLE
can we convert the .evtx to .txt files during the log collection

### ISSUE THREAD

**Issue by elnemss** [PowerShell/PrivateCloud.DiagnosticInfo#183]
### Summary of the new feature / enhancement

i was wondering if there is anyway while we are running the SDDC log collection to convert the .evtx files into .txt which will make it easier to check using Notepad ++ or any other software

**Comment by dl2n** [comment]
The tool captures event rendering information from the target system: these are the LocaleMetadata directories below the locations where .evtx are present. This allows Get-WinEvent (PS1) or wevtutil (or anything else using ETW) to show the event's friendly message without the need to pre-render all of the events in text form during the gather, which would dramatically increase the size of the payload.

This will get you started:

wevtutil qe path\to\somefile.evtx /lf /f:text /c:10
Get-WinEvent -Path path\to\somefile.evtx -MaxEvents 10
