### ISSUE TITLE
Add a timeout to prevent the script from running for many hours

### ISSUE THREAD

**Issue by cpuck** [PowerShell/PrivateCloud.DiagnosticInfo#190]
### Summary of the new feature / enhancement

Consider adding a timeout in the event the script gets stuck looping inside a data collection task.

- In version 1.1.38 the SDDC script ran for 34 hours and never completed. It was stuck on Running: GetNetView the majority of the time.
- Get-SDDCDiagnosticInfo (without -IncludeGetNetView) took 28 minutes to complete successfully.  Nothing in the output looked out of the ordinary.
- Running Get-NetView by itself completes in a reasonable amount of time.
- Get-SDDCDiagnosticInfo -IncludeGetNetView would also run for over 24 hours.

**Comment by PR-Liu** [comment]
Addressed by #189
