### ISSUE TITLE
Errors is generated when Get-SddcDiagnosticInfo is run remotely

### ISSUE THREAD

**Issue by janegilring** [PowerShell/PrivateCloud.DiagnosticInfo#96]
The following errors occurs when running Get-SddcDiagnosticInfo from a remote computer running Windows Server 2016:

2018-07-02T11:20:55 : Unhealthy VD
Get-VirtualDisk : Windows Storage Management Provider: An error was encountered while enumerating objects from subsystem "{38f9ffc1-f628-4510-bb45-a3d64ed3a080}:SS" on host "s2d1-05". Error encountered was MI_RESULT = "MI_RESULT_NOT_FOUND" (6).
At C:\Program Files\WindowsPowerShell\Modules\PrivateCloud.DiagnosticInfo\PrivateCloud.DiagnosticInfo.psm1:854 char:34
+                 $NonHealthyVDs = Get-VirtualDisk | where {$_.HealthSt ...
+                                  ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_VirtualDisk:ROOT/Microsoft/...SFT_VirtualDisk) [Get-VirtualDisk], CimException
    + FullyQualifiedErrorId : 4,Get-VirtualDisk
 
Get-VirtualDisk : Windows Storage Management Provider: An error was encountered while enumerating objects from subsystem "{7f6e18ea-9962-4ead-a993-45b8d96cdc10}:SS" on host "s2dtmp". Error encountered was MI_RESULT = "MI_RESULT_FAILED" (1).
At C:\Program Files\WindowsPowerShell\Modules\PrivateCloud.DiagnosticInfo\PrivateCloud.DiagnosticInfo.psm1:854 char:34
+                 $NonHealthyVDs = Get-VirtualDisk | where {$_.HealthSt ...
+                                  ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_VirtualDisk:ROOT/Microsoft/...SFT_VirtualDisk) [Get-VirtualDisk], CimException
    + FullyQualifiedErrorId : 4,Get-VirtualDisk
 
Get-VirtualDisk : Windows Storage Management Provider: An error was encountered while enumerating objects from subsystem "{f26c5e92-d8c7-11e7-bb33-806e6f6e6963}:SS" on host "s2d1-05". Error encountered was MI_RESULT = "MI_RESULT_NOT_FOUND" (6).
At C:\Program Files\WindowsPowerShell\Modules\PrivateCloud.DiagnosticInfo\PrivateCloud.DiagnosticInfo.psm1:854 char:34
+                 $NonHealthyVDs = Get-VirtualDisk | where {$_.HealthSt ...
+                                  ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_VirtualDisk:ROOT/Microsoft/...SFT_VirtualDisk) [Get-VirtualDisk], CimException
    + FullyQualifiedErrorId : 4,Get-VirtualDisk
 
Get-PhysicalExtent : Unspecified error 
At C:\Program Files\WindowsPowerShell\Modules\PrivateCloud.DiagnosticInfo\PrivateCloud.DiagnosticInfo.psm1:858 char:58
+ ...       $NonHealthyExtents = $NonHealthyVD | Get-PhysicalExtent |? Oper ...
+                                                ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_VirtualDis...indows/Stor...):CimInstance) [Get-PhysicalExtent], CimException
    + FullyQualifiedErrorId : HRESULT 0x80004005,Microsoft.Management.Infrastructure.CimCmdlets.InvokeCimMethodCommand,Get-PhysicalExtent
 
These errors do no occur when the command is executed locally on a node in the target cluster.

**Comment by dl2n** [comment]
Please see if you can reproduce this by simply calling Get-VirtualDisk. Assuming you can, open a Microsoft support case to root cause the underlying issue.

You’ll note the remoting is not correctly done here (Get-VirtualDisk lacks a -CimSession or subsystem object). This is fixed in 1.1.1, which is in the dev branch and which will land shortly.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by janegilring** [comment]
This turned out to be a local issue on the management server I was running the module from.
An old/stale storage subsystem was registered, which I solved by running this command:
Unregister-StorageSubSystem -UniqueId "{f26c5e92-d8c7-11e7-bb33-806e6f6e6963}:SS" -ProviderName "Windows Storage Management Provider" -Force
