### ISSUE TITLE
Recommendations for additional data to be collected

### ISSUE THREAD

**Issue by bilinear** [PowerShell/PrivateCloud.DiagnosticInfo#97]
fltmc and fltmc instances output - this will help determine if there is filter drivers loaded which can greatly impact reading/writing to cluster shared volumes.
Get-netadapterVMQ output - rss and ndis/qos settings are already collected, it seems strange to me that this is missing.

**Comment by dl2n** [comment]
added in the dev branch for 1.1.1, thanks ...
