### ISSUE TITLE
powershell constrained language mode blocks dot-source model for scriptblock passing

### ISSUE THREAD

**Issue by dl2n** [PowerShell/PrivateCloud.DiagnosticInfo#99]
Get-SddcDiagnosticInfo uses dot-sourcing language to pass the CommonFunc block to remote invoke-command sessions, which is not permitted in Powershell constrained language mode.

Convert to using persistent sessions into which we can invoke the CommonFunc block followed by the gathering block.

**Comment by visvel** [comment]
Fixed.
